version: '3.9'

services:
  client:
    build: ./client
    container_name: client-app
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    container_name: server-app
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
