version: '3.9'
services:
  client1:
    build: ./client
    ports:
      - "3000:80"
  client2:
    build: ./client2
    ports:
      - "3001:80"
  server:
    build: ./server
    ports:
      - "6000:6000"
