version: '3.9'

services:
  client1:
    build: ./client
    container_name: client-app
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network

  client2:
    build: ./client2
    container_name: client-app2
    ports:
      - "3001:80"   # Use a different host port to avoid collision with client1
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    container_name: server-app
    ports:
      - "6000:6000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
